<?php

function search_web_app()
{
    //PROD SITE
    /*wp_register_script( // the app build script generated by Webpack.
        'vue_search_app',
        'https://recipesforwellbeing.org/dist/build.js',
        array( 'wp-api' ),
        false,
        true
    );*/


    // STAGING SITE
    // register the Vue build script.
    /*wp_register_script( // the app build script generated by Webpack.
        'vue_search_app',
        'https://staging.recipesforwellbeing.org/dist/build.js',
        array( 'wp-api' ),
        false,
        true
    );*/


    //DEV SITE

    wp_register_script( // the app build script generated by Webpack.
        'vue_search_app',
        'http://127.0.0.1:8080/dist/build.js',
        array('wp-api'),
        false,
        true
    );

    $args = array(
        'numberposts' => -1,
    );

    $postsList = get_posts($args);

    $postListFiltered = array();
    foreach ($postsList as $post) {

        $postCategories = wp_get_post_categories($post->ID, array('fields' => 'ids'));
        $hasBlogCategory = in_array(196, $postCategories);
        $hasEventCategory = in_array(292, $postCategories);
        if (!$hasBlogCategory && !$hasEventCategory) {
            $newPost = $post;
            $postImageSrc = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'medium');
            //$postCategories = wp_get_post_categories($post->ID, array('fields' => 'ids'));
            $postTags = wp_get_post_tags($post->ID, array('fields' => 'ids'));
            if (is_array($postImageSrc)) {
                $newPost->imgSrc = $postImageSrc[0];
            }
            $newPost->post_date = strtotime($newPost->post_date);
            $newPost->categories = $postCategories;
            $newPost->tags = $postTags;
            $newPost->difficulties = wp_get_post_terms($newPost->ID, 'difficulty', array("fields" => "ids"));
            $newPost->durations = wp_get_post_terms($newPost->ID, 'duration', array("fields" => "ids"));
            $newPost->servings = wp_get_post_terms($newPost->ID, 'serving', array("fields" => "ids"));
            $newPost->domains = wp_get_post_terms($newPost->ID, 'domain', array("fields" => "ids"));
            $newPost->skills = wp_get_post_terms($newPost->ID, 'skill', array("fields" => "ids"));
            $newPost->intersections = wp_get_post_terms($newPost->ID, 'intersection', array("fields" => "ids"));
            $newPost->dishes = wp_get_post_terms($newPost->ID, 'dish', array("fields" => "ids"));
            $newPost->recipes = wp_get_post_terms($newPost->ID, 'recipe', array("fields" => "ids"));
            array_push($postListFiltered, $newPost);
        }
    }

    wp_localize_script(
        'vue_search_app', // vue script handle defined in wp_register_script.
        'wpData', // javascript object that will made availabe to Vue.
        array( // wordpress data to be made available to the Vue app in 'wpData'
            'template_directory_uri' => get_stylesheet_directory_uri(), // child theme directory path.
            'difficultiesList' => get_terms(array(
                'taxonomy' => 'difficulty',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'durationsList' => get_terms(array(
                'taxonomy' => 'duration',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'servingsList' => get_terms(array(
                'taxonomy' => 'serving',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'domainsList' => get_terms(array(
                'taxonomy' => 'domain',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'skillsList' => get_terms(array(
                'taxonomy' => 'skill',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'intersectionsList' => get_terms(array(
                'taxonomy' => 'intersection',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'dishesList' => get_terms(array(
                'taxonomy' => 'dish',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'recipesList' => get_terms(array(
                'taxonomy' => 'recipe',
                'hide_empty' => false,
                'fields' => 'all'
            )),
            'postsList' => $postListFiltered,
            'categoriesList' => get_categories(array(
                'fields' => 'all'
            )),
            'tagsList' => get_tags(array(
                'fields' => 'all'
            ))
        ));

    // PROD
    // enqueue the Vue app script with localized data.
    /*if (is_page('library')) {
        wp_enqueue_script('vue_search_app');
    }*/

    // STAGING
    // enqueue the Vue app script with localized data.
    /*if (is_page('library')) {
        wp_enqueue_script('vue_search_app');
    }*/

    // DEV
    // enqueue the Vue app script with localized data.
    if (is_page('wholebeing-library')) {
        wp_enqueue_script('vue_search_app');
    }
}

add_action('wp_enqueue_scripts', 'search_web_app');

